name: whatsapp
networks:
  default:
    name: whatsapp

services:
  database:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./volumes/redisDb:/data
    ports:
      - 6379:6379
