name: whatsapp
networks:
  default:
    name: whatsapp

services:
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: genos
      MONGO_INITDB_ROOT_PASSWORD: genos
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
